FROM connormanning/entwine:latest
MAINTAINER Connor Manning <connor@hobu.co>

ENV CC clang
ENV CXX clang++

RUN wget -qO- https://deb.nodesource.com/setup_4.x | bash -
RUN apt-get install -y nodejs supervisor
RUN rm -rf /var/lib/apt/lists/*

RUN npm install -g node-gyp && npm update npm -g && npm cache clean

ADD . /opt/greyhound
WORKDIR /opt/greyhound

RUN make && make install

EXPOSE 80
EXPOSE 443
EXPOSE 8989

CMD greyhound dockerstart && greyhound log

# Sample invocation:
#     docker run -it -p 8080:80 -v ~/data:/opt/greyhound local/greyhound

