#!/usr/bin/env bash

case $1 in
start)
    if [ $# -eq 2 ]; then
        if [ $2 == "-q" ] || [ $2 == "--quiet" ]; then
            echo "Using quiet"
            foreman start -f ProcfileQuiet&
        else
            echo "Usage: $0 {start|stop} [-q|--quiet]" >&2
        fi
    else
        foreman start&
    fi
    ;;
stop)
    pkill gh_*
    killall nodejs    # TODO Hipache workers don't seem to allow naming.
    ;;
*)
    echo "Usage: $0 {start|stop} [-q|--quiet]" >&2

esac

