#!/usr/bin/env bash

LOGPATH=/var/log/supervisor/greyhound.log

case $1 in
start)
    greyhound stop
    supervisorctl start greyhound
    ;;
stop)
    supervisorctl stop greyhound
    ;;
log)
    touch $LOGPATH && tail -f $LOGPATH
    ;;
dockerstart)
    supervisord -c /etc/supervisor/supervisord.conf
    ;;
*)
    echo "Usage: $0 {start|stop|log}" >&2
esac

