#!/usr/bin/env bash

case $1 in
start)
    if [ -e "/etc/init.d/gh_fe" ]
    then
        /etc/init.d/gh_fe start
    fi
    /etc/init.d/gh_ws start
    /etc/init.d/gh_db start
    /etc/init.d/gh_dist start
    /etc/init.d/gh_sh start
    /etc/init.d/gh_web start

    if [ -e "/etc/init.d/gh_mongo" ]
    then
        /etc/init.d/gh_mongo start
    fi
    ;;
stop)
    if [ -e "/etc/init.d/gh_fe" ]
    then
        /etc/init.d/gh_fe stop
    fi
    /etc/init.d/gh_ws stop
    /etc/init.d/gh_db stop
    /etc/init.d/gh_dist stop
    /etc/init.d/gh_sh stop
    /etc/init.d/gh_web stop

    if [ -e "/etc/init.d/gh_mongo" ]
    then
        /etc/init.d/gh_mongo stop
    fi

    echo -e "select 0\nflushdb" | redis-cli > /dev/null 2>&1;
    ;;
auto)
    # Add auto-launch services.
    if [ -e "/etc/init.d/gh_fe" ]
    then
        update-rc.d gh_fe defaults 95 05
    fi
    update-rc.d gh_ws defaults 96 04
    update-rc.d gh_db defaults 96 04
    update-rc.d gh_dist defaults 96 04
    update-rc.d gh_sh defaults 96 04
    update-rc.d gh_web defaults 96 04

    if [ -e "/etc/init.d/gh_mongo" ]
    then
        update-rc.d gh_mongo defaults 95 05
    fi
    ;;
rmauto)
    # Remove all auto-launch services.
    if [ -e "/etc/init.d/gh_fe" ]
    then
        update-rc.d -f gh_fe remove
    fi
    update-rc.d -f gh_ws remove
    update-rc.d -f gh_db remove
    update-rc.d -f gh_dist remove
    update-rc.d -f gh_sh remove
    update-rc.d -f gh_web remove

    if [ -e "/etc/init.d/gh_mongo" ]
    then
        update-rc.d -f gh_mongo remove
    fi
    ;;
status)
    for key in `echo "KEYS services/*" | redis-cli`; do
        echo `echo "GET $key" | redis-cli`
    done
    ;;
*)
    echo "Usage: $0 {start|stop|auto|rmauto|status}" >&2

esac

