#!/bin/bash
# chkconfig: 2345 95 05
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin

GH_ROOT=/var/greyhound/
LOG_ROOT=/var/log/greyhound/

COMPONENT=gh_fe
ROOT=$GH_ROOT/frontend-proxy/

case $1 in
    start)
        echo -e "select 0\nflushdb" | redis-cli > /dev/null 2>&1;

        nohup /usr/sbin/haproxy -f $ROOT/haproxy.cfg -d \
            1>>"$LOG_ROOT/$COMPONENT-proxy.txt" 2>&1 &
        echo $! > "$ROOT/$COMPONENT-proxy.pid";

        nohup /usr/bin/hipache -c $ROOT/hipache-config.json \
            1>>"$LOG_ROOT/$COMPONENT-hipache.txt" 2>&1 &
        echo $! > "$ROOT/$COMPONENT-hipache.pid";
        ;;
    stop)
        if [ -e "$ROOT/$COMPONENT-proxy.pid" ]
        then
            kill `cat $ROOT/$COMPONENT-proxy.pid` > /dev/null 2>&1;
            rm "$ROOT/$COMPONENT-proxy.pid";
        fi

        if [ -e "$ROOT/$COMPONENT-hipache.pid" ]
        then
            kill `cat $ROOT/$COMPONENT-hipache.pid` > /dev/null 2>&1;
            rm "$ROOT/$COMPONENT-hipache.pid";
        fi
        ;;
    *)
        echo "usage: /etc/init.d/$COMPONENT {start|stop}"
        ;;
esac
exit 0

