#!/bin/bash
# chkconfig: 2345 95 05
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin

COMPONENT=gh_pre

case $1 in
   start)

      nohup /usr/sbin/haproxy -f /var/greyhound/pre/frontend-proxy/haproxy.cfg -d 1>>"/var/log/$COMPONENT-proxy.txt" 2>&1 &
      echo $! > "$ROOT/$COMPONENT-proxy.pid";

      nohup mongod --dbpath /home/vagrant/data --port 21212 --logpath /home/vagrant/log.txt 1>>"/var/log/$COMPONENT-mongo.txt" 2>&1 &
      echo $! > "$ROOT/$COMPONENT-mongo.pid";

      nohup /usr/bin/hipache -c /var/greyhound/pre/frontend-proxy/hipache-config.json 1>>"/var/log/$COMPONENT-hipache.txt" 2>&1 &
      echo $! > "$ROOT/$COMPONENT-hipache.pid";

      ;;
    stop)
      kill `cat $ROOT/$COMPONENT-proxy.pid`;
      kill `cat $ROOT/$COMPONENT-mongo.pid`;
      kill `cat $ROOT/$COMPONENT-hipache.pid`;
      ;;
    *)
      echo "usage: /etc/init.d/$COMPONENT {start|stop}"
      ;;
esac
exit 0

