#!/bin/bash
# chkconfig: 2345 96 04
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin

COMPONENT=gh_web
ROOT=/var/greyhound/web

case $1 in
   start)
      nohup "node" "$ROOT/app.js" 1>>"/var/log/$COMPONENT.txt" 2>&1 &
      echo $! > "$ROOT/$COMPONENT.pid";
      ;;
    stop)
      kill `cat $ROOT/$COMPONENT.pid` ;;
    *)
      echo "usage: /etc/init.d/$COMPONENT {start|stop}" ;;
esac
exit 0

